<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>velmobil_simulation</name>
  <version>1.0.0</version>
  <description>Simulation configuration for GZ SIM</description>
  <maintainer email="troszczynskikamil@outlook.com">Kamil Troszczyński</maintainer>
  <maintainer email="milosz.piecha05@gmail.com">Miłosz Piecha</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <build_depend>ros_gz_bridge</build_depend>
  <build_depend>ros_gz_sim</build_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>xacro</exec_depend>

  <depend>control_msgs</depend>
  <depend>control_toolbox</depend>
  <depend>gz_ros2_control</depend>
  <depend>ira_laser_tools</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
